// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: transaction/test_drive.proto

package testDrive

import (
	fmt "fmt"
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for TestDrive service

func NewTestDriveEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for TestDrive service

type TestDriveService interface {
	// 新增试驾
	Add(ctx context.Context, in *TestDriveAddDto, opts ...client.CallOption) (*common.Response, error)
	// 删除试驾
	Delete(ctx context.Context, in *TestDriveDeleteDto, opts ...client.CallOption) (*common.Response, error)
	// 更新试驾
	Update(ctx context.Context, in *TestDriveUpdateDto, opts ...client.CallOption) (*common.Response, error)
	// 获取试驾列表
	List(ctx context.Context, in *common.Page, opts ...client.CallOption) (*common.Response, error)
}

type testDriveService struct {
	c    client.Client
	name string
}

func NewTestDriveService(name string, c client.Client) TestDriveService {
	return &testDriveService{
		c:    c,
		name: name,
	}
}

func (c *testDriveService) Add(ctx context.Context, in *TestDriveAddDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "TestDrive.Add", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testDriveService) Delete(ctx context.Context, in *TestDriveDeleteDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "TestDrive.Delete", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testDriveService) Update(ctx context.Context, in *TestDriveUpdateDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "TestDrive.Update", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testDriveService) List(ctx context.Context, in *common.Page, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "TestDrive.List", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TestDrive service

type TestDriveHandler interface {
	// 新增试驾
	Add(context.Context, *TestDriveAddDto, *common.Response) error
	// 删除试驾
	Delete(context.Context, *TestDriveDeleteDto, *common.Response) error
	// 更新试驾
	Update(context.Context, *TestDriveUpdateDto, *common.Response) error
	// 获取试驾列表
	List(context.Context, *common.Page, *common.Response) error
}

func RegisterTestDriveHandler(s server.Server, hdlr TestDriveHandler, opts ...server.HandlerOption) error {
	type testDrive interface {
		Add(ctx context.Context, in *TestDriveAddDto, out *common.Response) error
		Delete(ctx context.Context, in *TestDriveDeleteDto, out *common.Response) error
		Update(ctx context.Context, in *TestDriveUpdateDto, out *common.Response) error
		List(ctx context.Context, in *common.Page, out *common.Response) error
	}
	type TestDrive struct {
		testDrive
	}
	h := &testDriveHandler{hdlr}
	return s.Handle(s.NewHandler(&TestDrive{h}, opts...))
}

type testDriveHandler struct {
	TestDriveHandler
}

func (h *testDriveHandler) Add(ctx context.Context, in *TestDriveAddDto, out *common.Response) error {
	return h.TestDriveHandler.Add(ctx, in, out)
}

func (h *testDriveHandler) Delete(ctx context.Context, in *TestDriveDeleteDto, out *common.Response) error {
	return h.TestDriveHandler.Delete(ctx, in, out)
}

func (h *testDriveHandler) Update(ctx context.Context, in *TestDriveUpdateDto, out *common.Response) error {
	return h.TestDriveHandler.Update(ctx, in, out)
}

func (h *testDriveHandler) List(ctx context.Context, in *common.Page, out *common.Response) error {
	return h.TestDriveHandler.List(ctx, in, out)
}
